version: "3.8"

services:
  terminal-grounds-website:
    container_name: terminal-grounds-website
    build: .
    image: terminal-grounds-website:latest
    restart: unless-stopped
    ports:
      - "${HOST_PORT:-2161}:80"  # Default port 2161 (matching Bloom's timeline year)
    environment:
      - TZ=${TZ:-UTC}
      - NGINX_WORKER_PROCESSES=auto
      - NGINX_WORKER_CONNECTIONS=1024
    volumes:
      # Optional: Mount for persistent logs
      - ./logs:/var/log/nginx
    labels:
      # Auto-updating website with GitHub integration
      - "com.docker.compose.project=terminal-grounds"
      - "com.docker.compose.service=website-auto-update"
      # Traefik labels (adjust for your reverse proxy)
      - "traefik.enable=true"
      - "traefik.http.routers.tg-website.entrypoints=websecure"
      - "traefik.http.routers.tg-website.rule=Host(`${DOMAIN:-terminal-grounds.local}`)"
      - "traefik.http.routers.tg-website.tls.certresolver=letsencrypt"
      - "traefik.http.services.tg-website.loadbalancer.server.port=80"
      # Optional: Basic auth for development
      # - "traefik.http.middlewares.tg-auth.basicauth.users=admin:$$2y$$10$$..."
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks:
      - terminal-grounds-network

networks:
  terminal-grounds-network:
    driver: bridge